name: Codecov Upload

on:
  pull_request:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Apresentacao-da-Disciplina/P2-Conteudos/Atividades/Atividade-08

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run test:coverage

      - uses: codecov/codecov-action@v4
        with:
          directory: Apresentacao-da-Disciplina/P2-Conteudos/Atividades/Atividade-08/coverage