name: Codecov Upload

on:
  push:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Apresentacao-da-Disciplina/P2-Conteudos/Atividades/Atividade-08

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Coverage
        run: npm run test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          directory: Apresentacao-da-Disciplina/P2-Conteudos/Atividades/Atividade-08/coverage
